### ISSUE TITLE
Breaking change in minor version

### ISSUE THREAD

**Issue by natebrunette** [doctrine/lexer#34]
Upgrading from 1.0.0 to 1.1.0 led to unexpected breaks because of the new php version requirement.

**Comment by malarzm** [comment]
We do not consider bumping the PHP version in a minor version to be a BC break as composer will not allow you to install not compatible anyway. Here's blogpost from our page with details: https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html
