### ISSUE TITLE
1.2.0 not marked as maintained?

### ISSUE THREAD

**Issue by mglaman** [doctrine/lexer#39]
Per https://www.doctrine-project.org/projects/lexer.html, it shows that the latest minor releases are not maintained. Is this true? 1.2.0 was released a few months ago. Maybe the Doctrine website needs to be updated?

**Comment by SenseException** [comment]
This is because of an outdated `.doctrine-project.json` file on master-branch which is used to mark versions as maintained or not. The default state is `unmaintained`. You can create a PR to fix this if you like. You'll find this file in other Doctrine projects too as reference.

**Comment by alcaeus** [comment]
Fixed in db47018.

**Comment by mglaman** [comment]
Thanks!
