### ISSUE TITLE
Required new version tag for php 7.1

### ISSUE THREAD

**Issue by vgarun84** [doctrine/lexer#42]
can you pls make one tag at https://packagist.org/ for php7.1 at this commit id
https://github.com/doctrine/lexer/commit/db47018871229c8287a31d1520c62ce400ddcae8

May applications still running in symfony3.4 and php 7.1

**Comment by alcaeus** [comment]
Old versions still exist and can still be installed. The commit you reference simply updates the list of maintained branches on our website. Support for PHP 7.1 has been dropped in #28 and subsequently released as 1.1.0. If you want to use PHP 7.1, 1.0.2 will be installed by composer.
